AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'config/application.rb'

Metrics/LineLength:
  Exclude:
    - 'config/environments/production.rb'
    - 'db/seeds.rb'
    - 'features/**/*'
